apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow

name: workflow

on:
  push:
    branches:
      - main

permissions:
  id-token: write

jobs:
  build:
    steps:
      - name: Say hello
        uses: docker://golang:1.21.4-alpine3.18
        shell: sh
        run: |
          echo "hello world15"

      - uses: cloudbees-io/checkout@v1

      - name: build code
        uses: docker://golang:1.21.4-alpine3.18
        shell: sh
        run: |
          export GOPATH=$HOME/go
          export PATH=$PATH:$GOPATH/bin
          go version
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-w -s" -o build/app-main .

      - uses: cloudbees-io/configure-aws-credentials@v1
        id: aws-login
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::189768267137:role/cloudbees-ecr-publisher
          role-duration-seconds: "3600" # need to override default of 6h as this role has 1h max

      - name: Log in to ECR
        id: login-ecr
        uses: cloudbees-io/configure-ecr-credentials@v1

      - name: Build, tag, and push a container image to ECR
        uses: cloudbees-io/kaniko@v1
        with:
          destination: ${{ steps.aws-login.outputs.aws-account-id }}.dkr.ecr.us-east-1.amazonaws.com/hello-go-app:0.0.8
